### List all messages
GET http://localhost:3003/messages

### Create a new message
POST http://localhost:3003/messages
content-type: application/json

# A validação da pipe já está funcionando.
# O validador do DTO vai avaliar o corpo a seguir.
# Experimentar usar valores inválidos no POST:
{
  "content": "second message."
}

### Get a particular message
GET http://localhost:3003/messages/431235